### ISSUE TITLE
Validar place=locality com nome ^faz

### ISSUE THREAD

**Issue by naoliv** [OSMBrasil/validador-josm#20]
**place=locality** com nome de *^faz* provavelmente deve ser **place=farm**

**Comment by naoliv** [comment]
*[name =~ /^(?i)(Faz\.|Fazenda|Sítio|Chácara)/][place][place != farm] {
            throwError: tr("objeto provavelmente deve ser {0}=farm", "{0.key}");
    }

Pode?

**Comment by willemarcel** [comment]
de acordo!

**Comment by Skippern** [comment]
Acho sim, eu vi no shapefiles do `IJSN` que tem bairros ou distritos com `nome=Comunidade de Fazenda X`, credito que se `Fazenda X` e nome do bairro, deve coloque `Comunidade Fazenda X` ou similar no nome.

**Comment by naoliv** [comment]
Bairro o teste não pega justamente por causa desses casos (pra cá tem bairro que começa com Chácara, por exemplo).
