### ISSUE TITLE
maxspeed com unidades

### ISSUE THREAD

**Issue by Skippern** [OSMBrasil/validador-josm#39]
**maxspeed** deve usar valores numéricas somente, preferencia com valores do 10

Valores em km/h e sem unidades (60, não 60 km/h)

Valores imperiais (mph) não e usado no Brasil, mas deve ter unidade mph, existem lugares onde ha recalculado estes valores ao km/h - mas estes regras pode ser totalmente ignorado por brasil.

**Comment by naoliv** [comment]
4 anos depois, finalmente.
