### ISSUE TITLE
rua com ref NNNNN-NNN

### ISSUE THREAD

**Issue by Skippern** [OSMBrasil/validador-josm#43]
ref _NNNNN-NN_ provavelmente e o CEP e deve ser em **postal_code** ou **addr:postcode**

**Comment by naoliv** [comment]
O regex atualizado
https://overpass-turbo.eu/s/Col (vou corrigir os que existirem depois)

Vou deixar sem um teste específico, já que, de qualquer maneira, um aviso vai ser exibido para esses casos (dizendo que o `ref` está fora do padrão)
