### ISSUE TITLE
Unidades de conservação sem nome

### ISSUE THREAD

**Issue by astoff** [OSMBrasil/validador-josm#59]
Elementos com qualquer uma das seguintes tags
~~~~~
boundary=protected_area
boundary=national_park
leisure=nature_reserve
~~~~~
 devem obrigatoriamente ter um `name=*`, já que identificam áreas com um reconhecimento oficial.  (para pedaços de floresta preservada sem um reconhecimento oficial, usar simplesmente `natural=wood`.)

Áreas com `boundary=protected_area` precisam conter `protect_class=*`; mais precisamente `protect_class=[0-9]{1,2}[ab]?`

**Comment by naoliv** [comment]
O teste de `protect_class` serve para qualquer lugar (e não apenas para o Brasil). Essa parte eu vou ver se dá para ser incluído diretamente no JOSM.
