### ISSUE TITLE
IBGE:CD_ADMINIS=nao informado

### ISSUE THREAD

**Issue by naoliv** [OSMBrasil/validador-josm#60]
"nao informado" não adiciona nenhum tipo de informação útil nos dados

**Comment by jgpacker** [comment]
+1

**Comment by Skippern** [comment]
`IBGE:CD_ADMINIS=nao informado` pode ser tirado sem aviso

`IBGE:CD_ADMINIS` com valores diferente que `federal`, `estadual` ou `municipal` gera aviso.

**Comment by jgpacker** [comment]
@Skippern Não pode acontecer de a chave [`IBGE:CD_ADMINIS=*`](http://wiki.openstreetmap.org/wiki/Pt:Key:IBGE:CD_ADMINIS) ter valores múltiplos separados por ponto-e-vírgula?

**Comment by Skippern** [comment]
@jgpacker No meu conhecimento nao, o `IBGE:CD_ADMINIS` como importado tem somente os valores `federal` e `estadual`, acho que os trechos BR com `estadual` e onde o estado e responsável por manutenção. O valor `municipal` não conheço se for importado mas e lógico no mapa.

Em practico o `IBGE:CD_ADMINIS` denomear o nivel de órgão responsável por o rodovia, e o responsabilidade deve ser bem definido, um valor como `federal;estadual` e confuso.

Também pode dar um aviso (mas acho este pode ser complicado) se rodovias BR tem valor `estadual` sem fazer parte do relação do um rodovia estadual, e BR nunca deve ter valor `municipal`, mesmo rodovias estaduais somente deve ter o valor `estadual`, e o valor `municipal` somente deve existe nos rodovias que nem e federal nem estadual.

**Comment by naoliv** [comment]
Limpei todos "nao informado" que existiam.
