### ISSUE TITLE
crossing / level_crossing

### ISSUE THREAD

**Issue by willemarcel** [OSMBrasil/validador-josm#66]
Validar o uso incorreto de railway=crossing em um cruzamento de rua/estrada com ferrovia / railway=level_crossing sem estrada. E até mesmo a falta de level_crossing entre estrada/rua e ferrovia.

**Comment by Skippern** [comment]
`railway=crossing` e para pedestres, e não veiculo, este pode ser usado onde `highway=path`, `highway=footway` ou `highway=pedestrian` cruzam o ferrovia. Se o cruzamento e do tipo `railway=crossing` no um via que circulam veículos, deve ser em combinação com `motor_vehicle=no` no cruzamento. Qualquer outro cruzamento do ferrovia deve ser `railway=level_crossing`. 

Devemos avisar falta de `railway` e/ou `highway` no este duas. `level_crossing` e para onde tem circulação do veículos, e `crossing` somente para pedestres.

**Comment by naoliv** [comment]
```
way[railway =~ /^(abandoned|construction|disused|funicular|light_rail|miniature|monorail|narrow_gauge|preserved|rail|subway|tram)$/] > node { set .is_in_railway }
way[highway =~ /^(bridleway|cycleway|footway|path|steps)$/] > node[railway != crossing].is_in_railway {
        throwWarning: tr("should have railway=crossing where pedestrians cross");
        fixAdd: "railway=crossing";
}

way[highway =~ /^(bus_guideway|living_street|motorway|pedestrian|primary|raceway|residential|road|secondary|service|tertiary|track|trunk|unclassified)/] > node[railway != level_crossing].is_in_railway {
        throwWarning: tr("should have railway=level_crossing where road cross");
        fixAdd: "railway=level_crossing";
}
```

**Comment by naoliv** [comment]
https://josm.openstreetmap.de/ticket/11270
