### ISSUE TITLE
ponto ônibus com avenida, rua, estrada no nome

### ISSUE THREAD

**Issue by Skippern** [OSMBrasil/validador-josm#96]
Ponto de Ônibus pode ter nome da rua onde fica, então preciso excepção do warning `Nome do highway sem tag do highway`

**Comment by bonix-git** [comment]
Hi,

I had this type of warning before upload this data:

https://www.openstreetmap.org/node/4574171823#map=19/-23.59624/-46.52382


![captura de tela 2016-12-26 as 21 42 29](https://cloud.githubusercontent.com/assets/8519449/21487618/8ae504dc-cbb4-11e6-8691-e1dd8645292f.png)

**Comment by naoliv** [comment]
Nesse exemplo do Bonix é um `stop_position` com nome.

Para `platform` eu sei que faz sentido ter nome, mas `stop_position` também é nomeado? (ficando portanto 2 objetos com nome: a plataforma e a posição de parada)

**Comment by naoliv** [comment]
Bom, vou ignorar tudo o que tem `public_transport`

**Comment by bonix-git** [comment]
naoliv,

Desculpe a demora. Acabei colocando nome nos dois porque não sei como é a renderização.

Se para você basta um qual deles seria o mais indicado na sua opinião?

**Comment by Skippern** [comment]
`name` e necessario no `public_transport=stop_position` se não ha relação `stop_area`
